### ISSUE TITLE
Remove empty ___install() and ___uninstall()

### ISSUE THREAD

**Issue by LostKobrakai** [benbyford/PW-starter-modules#1]
https://github.com/benbyford/PW-starter-modules/blob/master/HelloUserYouSaved/HelloUserYouSaved.module#L54-L57

If ___install() or ___uninstall() aren't used just don't add those functions. Having an empty function body will prevent that inherited functionality of possible parent classes won't be called. That's why both functions – if used – should almost always call `parent::___install();` and `parent::___uninstall();` respectively. This is currently afaik only really needed for Process modules, which use the automatic page creation via the module config, but other functionality could always be added to pw later. Same goes for extending 3rd party modules.

**Comment by benbyford** [comment]
Thanks, amending now
