### ISSUE TITLE
Extended classes

### ISSUE THREAD

**Issue by LostKobrakai** [benbyford/PW-starter-modules#2]
https://github.com/benbyford/PW-starter-modules/blob/master/FrontEndRender/FrontEndRender.module#L17

No need to extend Page here, just use Wire.

**Comment by benbyford** [comment]
WireData you mean, or is ther Wire too? I was originally trying to add new functions to $page which is why it's still there by accident

**Comment by LostKobrakai** [comment]
WireData is often used, but if you won't need any functionality of WireData you could even just extend the abstract Wire class. WireData is nice, because it holds all the fancy functionality to add dynamic/runtime properties to the class.

Edit: A configurable module does probably need this WireData functionality to work correctly, which might make WireData favorable.
